### ISSUE TITLE
占个沙发

### ISSUE THREAD

**Issue by jschyz** [haozime/components#1]
初步看了好像有使用 [rollup-plugin-buble](https://gitlab.com/Rich-Harris/rollup-plugin-buble) 模块
但里面bublé编译工具，还是有一些特性未支持，比如
- Iterators
- generators
- [more](https://buble.surge.sh/guide/#unsupported-features)

如果编码时，使用了这些新特性，有可能编译不通过。

**Comment by haozime** [comment]
嗯，考虑到这个问题了，bublé只支持到 2015,考虑到前端编译 这些特性时 会产生很大量的代码并引入 runtime 库，不是很适合打包单文件模块情况时使用。
dev 模式时也阉割了 es2016 以上的特性，避免开发时正常，构建时出错。
